### ISSUE TITLE
Better example app

### ISSUE THREAD

**Issue by dbuschman7** [OrkestraCD/orkestra#3]
I cannot get a simple string parameter to show up in the client UI , could you upgrade the example to demonstrate the feature.

**Comment by joan38** [comment]
Hi @dbuschman7
Let me have a look now.

**Comment by joan38** [comment]
I added the example in `example/parameter`.

It seems that there is an issue with webjars: https://github.com/webjars/webjars/issues/1789
Which forces us to add a `ThisBuild / dependencyOverrides += "org.webjars.npm" % "js-tokens" % "3.0.2"` in every projects.
I'm looking at solving that in the lib directly.

**Comment by dbuschman7** [comment]
Thanks for the quick response and example. 
I saw the 'js-tokens' issues but was not sure if it was just my system. I added the ref myself and moved on.

**Comment by joan38** [comment]
@dbuschman7 I fixed it in the sbt-orkestra plugin and released 0.9.1 but I think this issue is major for the ScalaJS community and should be fixed on SBT or something.

**Comment by joan38** [comment]
@dbuschman7 Don't hesitate to ask anything if you have further issues.

**Comment by dbuschman7** [comment]
Sure, thanks. I will be distracted for a bit on another task. But I will be back.
